### ISSUE TITLE
Custom bottom bar

### ISSUE THREAD

**Issue by GovindSingh9447** [Dezenix/android-frontend-java#10]
### Description

Follow the contribution guidelines and code of conduct.
Create a custom bottom navigation bar
Make a smooth working custom bottom bar

**Comment by StarTrooper08** [comment]
Hello there👋,
I m SWOC contributor /participatant I would like to work on this issue!!

**Comment by GovindSingh9447** [comment]
Hey @StarTrooper08 ,
I am assigning this issues to you.

**Comment by arinmodi** [comment]
I ready to work on this

**Comment by arinmodi** [comment]
Hey @GovindSingh9447, i want to work on this, can you assign me this ?

**Comment by StarTrooper08** [comment]
I know I m taking time but I m working on this issue.

**Comment by arinmodi** [comment]
No problem @StarTrooper08

**Comment by arinmodi** [comment]
Can i work on this ?

**Comment by StarTrooper08** [comment]
I have completed the nav bar work.
Should I create pull request for complete code?
Or should I ignore some files/folders??

**Comment by GovindSingh9447** [comment]
Hey @StarTrooper08 , Create a PR of complete code.

**Comment by StarTrooper08** [comment]
Ok 👍

**Comment by StarTrooper08** [comment]
Created the Pull Request.
