### ISSUE TITLE
Create a slide bar

### ISSUE THREAD

**Issue by GovindSingh9447** [Dezenix/android-frontend-java#11]
### Description

Follow the contribution guidelines and code of conduct.
Create a slide bar with [Shimmer effect](https://imgr.search.brave.com/vSupQ1GCKtY1jK2b9OpkH9p-ZNyYmxZQgAF9XA73lwY/fit/1200/1000/ce/1/aHR0cHM6Ly9zMy5h/cC1zb3V0aC0xLmFt/YXpvbmF3cy5jb20v/bWluZG9ya3Mtc2Vy/dmVyLXVwbG9hZHMv/YmFubmVyLXNoaW1t/ZXItZWZmZWN0Lmpw/Zw)

**Comment by arinmodi** [comment]
Hey, i am swoc Participate and want to work on this issue

**Comment by GovindSingh9447** [comment]
@arinmodi you can work on it.
 [Shimmer effect](https://imgr.search.brave.com/vSupQ1GCKtY1jK2b9OpkH9p-ZNyYmxZQgAF9XA73lwY/fit/1200/1000/ce/1/aHR0cHM6Ly9zMy5h/cC1zb3V0aC0xLmFt/YXpvbmF3cy5jb20v/bWluZG9ya3Mtc2Vy/dmVyLXVwbG9hZHMv/YmFubmVyLXNoaW1t/ZXItZWZmZWN0Lmpw/Zw)

**Comment by arinmodi** [comment]
@GovindSingh9447, can you please add the screenshot for example purposes ? So that i can work well
