### ISSUE TITLE
Hidden Drawer bar 

### ISSUE THREAD

**Issue by GovindSingh9447** [Dezenix/android-frontend-java#12]
### Description

Follow guidelines and code of conduct
[Hidden Drawer bar](https://in.pinterest.com/pin/552816923013422706/) recreate the design.

**Comment by sekocoder** [comment]
Sir, I want to take this issue

**Comment by GovindSingh9447** [comment]
Sure @sekocoder, You can work on it.

**Comment by sekocoder** [comment]
Ok sir

**Comment by GovindSingh9447** [comment]
Looking awesome 👍
Yeah do it.

**Comment by sekocoder** [comment]
done sir

**Comment by sekocoder** [comment]
Done sir..there were some git files issues when I first uploaded it on GitHub but now I have resolved it sir and have made the pull request.
