### ISSUE TITLE
Chat Screen

### ISSUE THREAD

**Issue by GovindSingh9447** [Dezenix/android-frontend-java#16]
### Description

Follow the Guidelines and code of conduct.
Create a Chat list & Chat inbox like Instagram

**Comment by arinmodi** [comment]
Hey i want to work on it, please assign this to me

**Comment by GovindSingh9447** [comment]
Sure @arinmodi  you can work on it.
But don't exactly copy the instagram, you can take inspiration from them and use your creativity.

**Comment by arinmodi** [comment]
Hey @GovindSingh9447, Do i have to make app with database or just the ui with dummy data ?

**Comment by GovindSingh9447** [comment]
Make only UI

**Comment by arinmodi** [comment]
Hey, @GovindSingh9447 
here is the output,
![s1](https://user-images.githubusercontent.com/61725413/146632612-5b2419b0-cda8-45c4-95b2-14ee31a7fe85.png)
![s2](https://user-images.githubusercontent.com/61725413/146632619-0bf5df61-47cf-4b82-b62c-4b0372b60036.png)
![s3](https://user-images.githubusercontent.com/61725413/146632625-446a65ec-2846-4167-b874-e39d07b0a035.png)

and already sent an pull request.

let me know if there is any changes
