### ISSUE TITLE
Neumorphic Effect

### ISSUE THREAD

**Issue by GovindSingh9447** [Dezenix/android-frontend-java#20]
### Description

Follow the Guidelines and code of conduct when your pushing changes.
Create a e-commerce hone screen with Neumorphic effect

**Comment by arinmodi** [comment]
I want to work on this issue, please assign me

**Comment by GovindSingh9447** [comment]
@arinmodi yeah, you can start working.

**Comment by arinmodi** [comment]
hey, @GovindSingh9447 

here is the output,
![img1](https://user-images.githubusercontent.com/61725413/147041400-9692d1da-ccf7-4d14-aad6-e3593b6f002c.jpeg)
![img2](https://user-images.githubusercontent.com/61725413/147041410-09e70ec8-826c-4d8c-b294-a86da29a37ec.jpeg)
![img3](https://user-images.githubusercontent.com/61725413/147041418-a3713cde-56f5-49ba-bc5b-d7ae5d9ed75e.jpeg)

is this ok ?, should I make pull request ?

**Comment by GovindSingh9447** [comment]
> hey, @GovindSingh9447
> 
> here is the output, ![img1](https://user-images.githubusercontent.com/61725413/147041400-9692d1da-ccf7-4d14-aad6-e3593b6f002c.jpeg) ![img2](https://user-images.githubusercontent.com/61725413/147041410-09e70ec8-826c-4d8c-b294-a86da29a37ec.jpeg) ![img3](https://user-images.githubusercontent.com/61725413/147041418-a3713cde-56f5-49ba-bc5b-d7ae5d9ed75e.jpeg)
> 
> is this ok ?, should I make pull request ?

cool!!
@arinmodi  make a PR

**Comment by arinmodi** [comment]
ok
