### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by GovindSingh9447** [Dezenix/android-frontend-java#22]
### Description

Follow the Guidelines and code of conduct.
Create the weather app UI [like this](https://dribbble.com/shots/15292603-Weather-Conceptual-App-Design/attachments/7046975?mode=media).

**Comment by arinmodi** [comment]
Hey, i am available for this

**Comment by arinmodi** [comment]
Do i have to make exact same as given ?

**Comment by GovindSingh9447** [comment]
> Do i have to make exact same as given ?

Naah! You can take it as an idea.

**Comment by arinmodi** [comment]
Hey, @GovindSingh9447 

Here is my output : 

![s1](https://user-images.githubusercontent.com/61725413/147860911-acb3a23b-dbd3-4558-b74d-49ed31690ec9.png)

![s2](https://user-images.githubusercontent.com/61725413/147860934-dcb1590c-8eb9-47d8-bd3b-c99287b1f0aa.png)

![s3](https://user-images.githubusercontent.com/61725413/147860942-b1af1f0d-47d8-4080-85af-4a246ce59489.png)

I already made a pr.
