### ISSUE TITLE
Music App

### ISSUE THREAD

**Issue by GovindSingh9447** [Dezenix/android-frontend-java#26]
### Description

Follow the contribution guidelines and code of conduct
Develop a Music App:-
-Splash screen
-Login Screen
-Register Screen
-Home Screen (Where you can show Best music, New release, diff artist songs, etc. )
-Search Screen
-Music Player Screen
-Playlist/Library Screen

**Comment by arinmodi** [comment]
I am available for this, please assign this to me.

Do i have to make the whole app or just the ui ?

**Comment by GovindSingh9447** [comment]
> I am available for this, please assign this to me.
> 
> Do i have to make the whole app or just the ui ?

Just make UI

**Comment by arinmodi** [comment]
Ok

**Comment by arinmodi** [comment]
Hey, i made the PR

**Comment by GovindSingh9447** [comment]
Good work @arinmodi
