### ISSUE TITLE
Login and Register screens

### ISSUE THREAD

**Issue by Kajal13081** [Dezenix/android-frontend-java#4]
### Description

I would like to code for login and register screens for mobile. I will use animation and material design. 
@thepranaygupta, @garvitraj assign me this issue please.

**Comment by GovindSingh9447** [comment]
You can go with issues

**Comment by Kajal13081** [comment]
@GovindSingh9447 Can you please create android directory so that I can make project here. I have made the project on my local system but I dont know how to add the project in this repo.
