### ISSUE TITLE
Splash Screen(Animation) in Android 

### ISSUE THREAD

**Issue by anmol20112000** [Dezenix/android-frontend-java#6]
I would like to code for Splash Screen( with Animations) . I will use animation and material design.
assign me this issue please. @GovindSingh9447

**Comment by GovindSingh9447** [comment]
Anmol now you can proceed.

**Comment by anmol20112000** [comment]
> Anmol now you can proceed.

@GovindSingh9447  but why you closed the issue?

**Comment by GovindSingh9447** [comment]
@anmol20112000  Now you can work on it.

**Comment by Kajal13081** [comment]
@anmol20112000 How are you adding the project in this repo? There is not any android directory.

**Comment by anmol20112000** [comment]
> @anmol20112000 How are you adding the project in this repo? There is not any android directory. 

Actually i also didn't have any idea regarding this... I m thinking this too & What about ur issue  login & register screen ..in which directory  u will pull the code..?

**Comment by Kajal13081** [comment]
> > @anmol20112000 How are you adding the project in this repo? There is not any android directory.
> 
> Actually i also didn't have any idea regarding this... I m thinking this too & What about ur issue login & register screen ..in which directory u will pull the code..?

I created project on android studio and then I created directory in forked repo and copied the app project which I made and pasted there.

**Comment by anmol20112000** [comment]
> > > @anmol20112000 How are you adding the project in this repo? There is not any android directory.
> > 
> > Actually i also didn't have any idea regarding this... I m thinking this too & What about ur issue login & register screen ..in which directory u will pull the code..?
> 
> I created project on android studio and then I created directory in forked repo and copied the app project which I made and pasted there.

Ohh nice💯..i think i also have to this..🤷🏼‍♂️..else i have no other option..
